addons:
  apt:
    sources:
      - ubuntu
    packages:
      - gcc-4.8
      - g++-4.8
      - wget
      # Package list from http://bazel.io/docs/install.html
      - openjdk-8-jdk
      - openjdk-8-source
      - pkg-config
      - zip
      - zlib1g-dev

# Eventually, Bazel will have binary packages and we'll be able to
# just download a prebuilt distribution of Bazel. For now, build it
# from source every time.
before_install:
  - wget 'https://github.com/bazelbuild/bazel/releases/download/0.1.4/bazel-0.1.4-installer-linux-x86_64.sh'
  - chmod +x bazel-0.1.4-installer-linux-x86_64.sh
  - ./bazel-0.1.4-installer-linux-x86_64.sh --user
  - cat ~/.bazelrc >> .bazelrc
  - touch WORKSPACE

script:
  - bazel build //test:build_sanity
